name: neuroglancer-demo
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - requests
  - h5py
  - tqdm
  - pillow
  - jupyterlab
  - jupyter-server-proxy
  - pip
  - pip:
    - neuroglancer
    - cloud-volume
