channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.19.2
  - requests=2.24.0
  - h5py=2.10.0
  - tqdm=4.50.2
  - pillow==8.0.0
  - jupyterlab=2.2.8
  - jupyter-server-proxy=1.5.0
  - pip
  - pip:
    - neuroglancer==2.13
    - cloud-volume==3.1.0
