channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.3
  - numpy==1.17.3
  - requests==2.22.0
  - h5py==2.9.0
  - tqdm==4.36.1
  - pillow==6.2.1
  - jupyterlab==1.1.3
  - jupyter-server-proxy==1.1.0
  - pip
  - pip:
    - neuroglancer==1.1.6
    - cloud-volume==0.65.1
